### ISSUE TITLE
raspinfo@1 failing

### ISSUE THREAD

**Issue by ferventpiranha** [AndrewFromMelbourne/raspifb16#1]
on the latest Jessie Lite, raspinfo@1 works for a few seconds then fails. systemctl status raspinfo@1 shows the following:

raspinfo@1.service - Display Raspberry Pi specific system information directly on the framebuffer.
   Loaded: loaded (/etc/systemd/system/raspinfo@.service; enabled)
   Active: failed (Result: signal) since Thu 2016-02-25 08:16:00 EST; 14min ago
  Process: 348 ExecStart=/usr/local/bin/raspinfo --daemon --device /dev/fb%i --pidfile /var/run/raspinfo%i.pid (code=exited, status=0/SUCCESS)
 Main PID: 386 (code=killed, signal=SEGV)

**Comment by AndrewFromMelbourne** [comment]
Hi, I will have a look over the weekend. Is there any chance that a core file was created when it SEGVed? If so it would help me work out where it is crashing.

**Comment by ferventpiranha** [comment]
Thank you. I love the functionality, I just can't get it to work. Just so you know I'm a total noob when it comes to all of this.

**Comment by AndrewFromMelbourne** [comment]
You are welcome. I am sorry I haven't had any time to look at this issue. 

Could you tell me the Raspberry Pi model you are using? 

Are you using a small TFT display? If so which one?

I am not sure if this will help me narrow down the problem. I have never tried using the program on Rasbian Lite, so there may be something going on there. I will try Raspbian Lite when I have some time.

Sorry for the delay.

**Comment by ferventpiranha** [comment]
It's a Pi 2. By Raspbian Lite I mean I'm running the Lite version of the official Raspbian Jessie release. It just doesn't have a lot of the educational and game stuff pre-loaded. It's on their main release page: https://www.raspberrypi.org/downloads/raspbian/.

I'm running the Adafruit PiTFT Plus 3.5" found here: https://www.adafruit.com/products/2441. I've also loaded their frame buffer library found here: https://learn.adafruit.com/adafruit-pitft-3-dot-5-touch-screen-for-raspberry-pi/easy-install. I did all of the steps documented in their DIY installer script - it's just a few apt-gets and one setup step.

The fact that it works fine for a few seconds then cuts out (and requires a reboot to start again) is what's odd to me.

**Comment by AndrewFromMelbourne** [comment]
Thanks, that may help.

**Comment by AndrewFromMelbourne** [comment]
I haven't forgotten about this, but haven't had any time to look at it!

**Comment by ferventpiranha** [comment]
I would love to get this solved. If there's anything I can do to help please let me know.

**Comment by AndrewFromMelbourne** [comment]
Hi, yes I am sorry I have had very little time recently. Can I suggest running the raspinfo program from a terminal, rather than install it as a service.

```
cd raspifb16
git pull
mkdir build
cd build
cmake ..
make
./bin/raspinfo
```

Then let me know if any errors are reported. There is also a test program, you could try running that

```
./bin/raspifb16test
```

And let me know what is displayed on the screen.

**Comment by AndrewFromMelbourne** [comment]
No response in 7.5 years.

**Comment by ferventpiranha** [comment]
Not sure if this reply will get to you or just get lost in github, but thank you so much for getting back to this project. Sorry that I missed your reply years ago and that project was lost a few home moves ago I think. Thank you again for your time!

________________________________
