### ISSUE TITLE
libraspifb16 API documentation

### ISSUE THREAD

**Issue by briskt** [AndrewFromMelbourne/raspifb16#2]
Have you written any documentation for the libraspifb16 API? It seems like a perfect library for basic small TFT displays, unlike I've found anywhere else. If you haven't already written it, I'll just study the code.

**Comment by AndrewFromMelbourne** [comment]
No I don't have any documentation. The test program test.cxx  is probably a good place to start. If you have any questions please let me know.

**Comment by briskt** [comment]
Thanks. I started with going through the header files, taking notes as I went. Then moved the libraries and headers to /usr/local/lib and /usr/local/include and compiled test.cxx. It's becoming more clear how to use it. Thanks for providing this library.
